// Generated by tools/gen-icon.py from Marketing/app-icon.jpeg. Do not hand-edit.
package dev.localagent.workstation.ui

/**
 * The app icon, as geometry the app can draw for itself.
 *
 * Everything is in the 108-unit grid Android hands an adaptive icon, so a mark drawn
 * on a Box screen and the icon on the home screen are the same drawing at different
 * scales rather than two things that merely resemble each other.
 */
internal object BoxMarkArt {
    /** The three faces of the cube, as one path with three subpaths. */
    const val PATH = "M53.56,24.28A0.83,0.83 0 0 1 54.44,24.28L74.64,37.02A0.83,0.83 0 0 1 74.64,38.42L54.44,51.12A0.83,0.83 0 0 1 53.56,51.12L33.36,38.42A0.83,0.83 0 0 1 33.36,37.02Z M29.16,43.38A0.83,0.83 0 0 1 30.42,42.67L48.33,53.68A0.83,0.83 0 0 1 48.33,55.09L43.04,58.29A1.55,1.55 0 0 0 43.02,60.93L52.5,66.78A0.83,0.83 0 0 1 52.89,67.49L52.89,82.5A0.83,0.83 0 0 1 51.63,83.2L29.54,69.28A0.83,0.83 0 0 1 29.16,68.58Z M78.84,68.58A0.83,0.83 0 0 1 78.46,69.28L56.37,83.2A0.83,0.83 0 0 1 55.11,82.5L55.11,67.49A0.83,0.83 0 0 1 55.5,66.78L64.98,60.93A1.55,1.55 0 0 0 64.96,58.29L59.67,55.09A0.83,0.83 0 0 1 59.67,53.68L77.58,42.67A0.83,0.83 0 0 1 78.84,43.38Z"

    /** The 72-unit window a launcher mask actually shows of that grid. */
    const val WINDOW = 72f
    const val INSET = 18f

    /** A lit face, and the plate behind it, sampled from the artwork. */
    const val FACE = 0xFFF8F8F8
    const val HAZE = 0xFF111C0E
    const val HAZE_MID = 0xFF0D120C

    /**
     * The seam's glow, as (stroke width, alpha) laid down widest first. A vector
     * cannot blur, so the bloom is a stack of round-joined strokes fitted to the
     * artwork's measured falloff.
     */
    val GLOW = listOf(
        8.0f to 0.11f,
        6.2f to 0.04f,
        4.9f to 0.048f,
        3.8f to 0.056f,
        2.9f to 0.067f,
        2.2f to 0.076f,
        1.6f to 0.114f,
        1.1f to 0.168f,
        0.68f to 0.244f,
        0.3f to 0.561f,
    )
}
